export default {
  BASE_ASSET: "BTC",
  QUOTE_ASSET: "USDT",
  SYMBOL: "BTCUSDT",
  LEVERAGE: 125,
  INITIAL_QUANTITY: 0.001,
  POSITION_SCALE_OUT_RATE: 1.1,
  RSI_OVERBOUGHT: 70,
  RSI_OVERSOLD: 30
};
